@Library('ci-shared-library') _

dockerPromoteToProd(
    valuesPath: 'helm/values.yaml',
    imageRepositoryYqPath: '.apps.myService.image.repository',
    imageTagYqPath: '.apps.myService.image.tag',
    artifactoryDevRegistry: 'artifactory-dev.example.com',
    artifactoryDevRepository: 'docker-dev-local',
    artifactoryProdRegistry: 'artifactory-prod.example.com',
    artifactoryProdRepository: 'docker-prod-local',
    artifactoryCredentialsId: 'artifactory-docker'
)
