@Library('ci-shared-library') _

dockerBuildAndDeployToDev(
    imageName: 'my-service',
    deploymentRepoUrl: 'ssh://git@git.example.com:7999/platform/deployment.git',
    deploymentBranch: 'devel',
    valuesPath: 'helm/values.yaml',
    imageRepositoryYqPath: '.apps.myService.image.repository',
    imageTagYqPath: '.apps.myService.image.tag',
    dockerBuildArgs: '''
NODE_ENV=production
PUBLIC_PATH=/my-service
''',
    artifactoryDevRegistry: 'artifactory-dev.example.com',
    artifactoryDevRepository: 'docker-dev-local',
    artifactoryDevCredentialsId: 'artifactory-dev-docker',
    gitCredentialsId: 'deployment-git-ssh',
    deploymentGitSshHost: 'git.example.com',
    deploymentGitSshPort: '7999',
    gitAuthorName: 'jenkins',
    gitAuthorEmail: 'jenkins@example.com'
)
