@Library('ci-shared-library') _

dockerBuildAndDeployToDev(
    imageNameDefault: 'my-service',
    deploymentRepoUrlDefault: 'ssh://git@git.example.com:7999/platform/deployment.git',
    deploymentBranchDefault: 'devel',
    valuesPathDefault: 'helm/values.yaml',
    imageRepositoryYqPathDefault: '.apps.myService.image.repository',
    imageTagYqPathDefault: '.apps.myService.image.tag',
    dockerBuildArgsDefault: '''
NODE_ENV=production
PUBLIC_PATH=/my-service
''',
    artifactoryDevRegistryDefault: 'artifactory-dev.example.com',
    artifactoryDevRepositoryDefault: 'docker-dev-local',
    artifactoryDevCredentialsIdDefault: 'artifactory-dev-docker',
    gitCredentialsIdDefault: 'deployment-git-ssh',
    deploymentGitSshHostDefault: 'git.example.com',
    deploymentGitSshPortDefault: '7999',
    gitAuthorNameDefault: 'jenkins',
    gitAuthorEmailDefault: 'jenkins@example.com'
)
