@Library('ci-shared-library') _

dockerBuildAndDeployToDev(
    imageNameDefault: 'my-service',
    deploymentRepoUrlDefault: 'https://bitbucket.example.com/scm/platform/deployment.git',
    deploymentBranchDefault: 'devel',
    valuesDevPathDefault: 'helm/values-dev.yaml',
    devImageRepositoryYqPathDefault: '.apps.myService.image.repository',
    devImageTagYqPathDefault: '.apps.myService.image.tag',
    artifactoryDevRegistryDefault: 'artifactory-dev.example.com',
    artifactoryDevRepositoryDefault: 'docker-dev-local',
    artifactoryDevCredentialsIdDefault: 'artifactory-dev-docker',
    bitbucketCredentialsIdDefault: 'bitbucket-git',
    gitAuthorNameDefault: 'jenkins',
    gitAuthorEmailDefault: 'jenkins@example.com'
)
